// Generates fork_countries.go: the Spanish name of every country in
// ../handler/assets/phone-data.json, from the CLDR data Node ships (Intl.DisplayNames).
//
//   cd internal/webhook && node fork_countries.gen.mjs && gofmt -w fork_countries.go
//
// Re-run it whenever phone-data.json gains a country; TestCountryNameES_everyCountry fails
// until then.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const data = JSON.parse(fs.readFileSync(path.join(here, '../handler/assets/phone-data.json'), 'utf8'));
const names = new Intl.DisplayNames(['es'], { type: 'region' });

const codes = [...new Set(data.countries.map(([cc]) => cc))].sort();
const lines = codes.map((cc) => {
  const name = names.of(cc);
  if (!name || name === cc) {
    throw new Error(`no Spanish name for ${cc}`);
  }
  return `\t${JSON.stringify(cc)}: ${JSON.stringify(name)},`;
});

const out = `// Code generated by fork_countries.gen.mjs from ../handler/assets/phone-data.json; DO NOT EDIT.

package webhook

// countryNamesES is the Spanish (CLDR) name of every country in phone-data.json.
var countryNamesES = map[string]string{
${lines.join('\n')}
}
`;
fs.writeFileSync(path.join(here, 'fork_countries.go'), out);
console.log(`fork_countries.go: ${codes.length} countries`);
